--- # stop broker and agent and hosted engine for ovirt
- hosts: all
  connection: ssh
  gather_facts: smart
  remote_user: root
  tasks:
  - name: stop HE VM
    shell: 'hosted-engine --vm-shutdown'
    run_once: yes
  - name: Pause for hosted-engine VM shutdown
    pause:
      minutes: 1
      echo: no
      prompt: "Waiting 1 minute to allow hosted-engine VM to shut down"
    run_once: yes
  - name: stop broker
    service:
      name: ovirt-ha-broker
      state: stopped
  - name: stop agent
    service:
      name: ovirt-ha-agent
      state: stopped
  - name: Pause for HE VM shutdown
    pause:
      minutes: 1
      echo: no
      prompt: "Waiting 1 minute to allow things to settle"
    run_once: yes
  - name: disconnect hosted-engine storage
    shell: 'hosted-engine --disconnect-storage'
    run_once: yes
  - name: notify user
    debug: msg="You may now stop/shut-down the storage server/volumes/etc, and power down the oVirt hypervisor hosts."
