--- # stop broker and agent for ovirt
- hosts: all
  connection: ssh
  gather_facts: smart
  remote_user: root
  serial: no
  tasks:
  - name: stop broker
    service:
      name: ovirt-ha-broker
      state: stopped
  - name: stop agent
    service:
      name: ovirt-ha-agent
      state: stopped
